config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :questions
  devise_for :users
  resources :employees
  get 'home/index'
  get 'home/landing'
  get 'home/launch'
  delete 'home/launch'
  get 'home/questionaire'
  post 'home/questionaire'
  get 'home/confirmation'
  get 'home/signoutt'
  get 'home/failed'
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [ :index, :edit, :update, :destroy, :show ]
  before_action :correct_user, only: [:index, :edit, :update, :destroy, :show ]
  # GET /questions or /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = current_user.questions.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @question = current_user.questions.find_by(id: params[:id])
    # redirect_to root_path, notice: "Not Authorized" if @employee.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:attestation, :user_id)
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :attestation %>
    <%= form.text_area :attestation, class:"form-control"%>
  </div>
  <br/>

<%= form.number_field :user_id, id: :question_user_id, value:current_user.id, type:"hidden" %>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
  <br/>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

 
<%= link_to 'Back', :back, class:"btn btn-dark" %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Attestation</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
    <% if question.user == current_user %>
      <tr>
        <td><%= question.attestation %></td>        
        <td><%= link_to 'Edit', edit_question_path(question), class:"btn btn-dark btn-sm" %></td>
        <td><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm " %></td>
      </tr>
      <% end%>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path, class:"btn btn-primary" %>
<%= link_to 'Back', home_landing_path, class:"btn btn-dark" %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', :back, class:"btn btn-dark" %>

app/views/questions/show.html.erb
<div class="card">
<p>
  <strong>Attestation:</strong>
  <%= @question.attestation %>
</p>

</div>

<%= link_to 'Edit', edit_question_path(@question), class:"btn btn-secondary" %> 
<%= link_to 'Back', :back, class:"btn btn-dark" %>