config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :questions
  devise_for :users
  resources :employees
  get 'home/index'
  get 'home/landing'
  get 'home/launch'
  delete 'home/launch'
  get 'home/questionaire'
  post 'home/questionaire'
  get 'home/confirmation'
  get 'home/signoutt'
  get 'home/failed'
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/guest.rb
class Guest < ApplicationRecord
    belongs_to :user
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [ :index, :edit, :update, :destroy, :show ]
  before_action :correct_user, only: [:index, :edit, :update, :destroy, :show ]

  # GET /guests or /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1 or /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = current_user.guests.build
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests or /guests.json
  def create
    @guest = current_user.guests.build(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to home_questionaire_path(:guest_name => @guest.last_name << @guest.first_name,:id => @guest.id), notice: "Welcome #{@guest.first_name} please answer all questions." }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1 or /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: "Guest was successfully updated." }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1 or /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: "Guest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def guest_params
      params.require(:guest).permit(:first_name, :last_name, :answered_yes, :user_id, :signed_in)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= link_to "", home_launch_path, class:"btn-close", style:"position:absolute;top:0;right:0;" %>
<%= form_with(model: guest) do |form| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
        <% guest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br/>
  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
  <br/>
    
  
  <%= form.number_field :user_id, id: :guest_user_id, value:current_user.id, type:"hidden" %>
  
  
  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
  <br/>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guests</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Answered yes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.first_name %></td>
        <td><%= guest.last_name %></td>
        <td><%= guest.answered_yes %></td>
        <td><%= guest.user_id %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Back', :back, class:"btn btn-dark" %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @guest.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @guest.last_name %>
</p>

<p>
  <strong>Answered yes:</strong>
  <%= @guest.answered_yes %>
</p>

<p>
  <strong>User:</strong>
  <%= @guest.user_id %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>