config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :questions
  devise_for :users
  resources :employees
  get 'home/index'
  get 'home/landing'
  get 'home/launch'
  delete 'home/launch'
  get 'home/questionaire'
  post 'home/questionaire'
  get 'home/confirmation'
  get 'home/signoutt'
  get 'home/failed'
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
    
    def self.search(search)
        if search
            #employeename = Employee.find_by(first_name: search)
            employeename = Employee.where("lower(first_name) = ?", search.downcase).first
            if employeename
                self.where(id: employeename)
            else
                @employees = Employee.all
            end
        else
            @employees = Employee.all
        end
    end
    
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [ :index, :edit, :update, :destroy, :show ]
  before_action :correct_user, only: [:index, :edit, :update, :destroy, :show ]
  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    # @employee = Employee.new
    @employee = current_user.employees.build
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    #@employee = Employee.new(employee_params)
    @employee = current_user.employees.build(employee_params)
    
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully deleted." }
      format.json { head :no_content }
    end
  end

def correct_user
  @employee = current_user.employees.find_by(id: params[:id])
  # redirect_to root_path, notice: "Not Authorized" if @employee.nil?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :title, :user_id, :search, :answered_yes)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br/>
  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
  <br/>
  <div class="field form-group">
    
    <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
  </div>
    
  
  <%= form.number_field :user_id, id: :employee_user_id, value:current_user.id, type:"hidden" %>
  
  
  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
  <br/>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

 
<%= link_to 'Back', :back, class:"btn btn-dark" %>

app/views/employees/index.html.erb
<h1>Employee List</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
    <% if employee.user == current_user %>
      <tr>
        <td><%= employee.first_name + " " + employee.last_name %></td>
        <td><%= employee.title %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee), class:"btn btn-dark btn-sm" %></td>
        <td><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path, class:"btn btn-primary" %>
<%= link_to 'Back', home_landing_path, class:"btn btn-dark" %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', :back, class:"btn btn-dark" %>

app/views/employees/show.html.erb
<div class="card">
<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @employee.title %>
</p>
</div>
<%= link_to 'Edit', edit_employee_path(@employee), class:"btn btn-secondary" %> 
<%= link_to 'Back', :back, class:"btn btn-dark" %>