config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :questions
  devise_for :users
  resources :employees
  get 'home/index'
  get 'home/landing'
  get 'home/launch'
  delete 'home/launch'
  get 'home/questionaire'
  post 'home/questionaire'
  get 'home/confirmation'
  get 'home/signoutt'
  get 'home/failed'
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  def landing
  end
  def launch
    @employees = current_user.employees.search(params[:search]).order('id ASC')
    signout_guest()
  end
  def questionaire
    if params[:guest_name].present?
      @current_employee = Guest.find(params[:id])
      @is_guest = true
    else
      @current_employee = Employee.find(params[:id])
    end
    @questions = current_user.questions.order('id ASC') 
    if params[:add_answer]
      array = Array.new
      array = array.push(@current_employee.answered_yes)
      array = array.push(params[:add_answer])
      joined = array.join('~')
      @current_employee.update(answered_yes: joined)
    end
    if params[:commit].present?
      onlyanswers = request.request_parameters
      onlyanswers = onlyanswers.except(:id, :commit, :authenticity_token, :guest_name)
      if onlyanswers.count != @questions.count
        flash.now.notice = "Please answer each question" and return
      end
      values = onlyanswers.values
      values.delete("")
      joined = values.join('~')
      if joined.empty?
        @current_employee.update(signed_in: true)
      else
        @current_employee.update(answered_yes: joined)
        redirect_to "/home/failed" and return
      end
      redirect_to "/home/confirmation" and return
    end
    if @current_employee.signed_in
      @current_employee.update(signed_in: false)
      redirect_to "/home/signoutt" and return    
    end    
  end
  def confirmation
  end
  def signoutt
    signout_guest()
  end
  def failed
    signout_guest()
  end
  def signout_guest
    @guests = current_user.guests.all
    @guests.each do |guest| 
      if guest.signed_in != true
        guest.destroy
      end
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link active" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Manage", home_landing_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/confirmation.html.erb
<head>
<script type="text/javascript">
function delayedRedirect(){
    window.location = "/home/launch";
}
setTimeout('delayedRedirect()', 2500);
</script>
</head>
<body>
<h1 class="position-absolute top-50 start-50 translate-middle">Signed in Successfully!</h1>
</body>

app/views/home/failed.html.erb
<head>
<script type="text/javascript">
function delayedRedirect(){
    window.location = "/home/launch";
}
setTimeout('delayedRedirect()', 30000);
</script>
</head>
<body>
<section class="position-absolute top-50 start-50 translate-middle">
    <h1>Your answers indicate a risk of Covid exposure:</h1>
    <h2>Please leave the premesis and contact a Supervisor.</h2>
    <br/>
    <div class="d-grid gap-2 col-4 mx-auto">
        <%= link_to "Acknowledge", home_launch_path, class:"btn btn-primary" %>
    </div>
</section>
</body>

app/views/home/index.html.erb
<h1>Covid Screener Questionare application</h1>
<br/>
<h3>Who should be screened?</h3>
<ul>
Businesses can consider screening employees for symptoms, but this may have a limited effect as the
virus that causes COVID-19 can also be spread by people who are not showing symptoms.
</ul>
<h3>
When should screening occur? 
</h3>
<ul>
If screening is done, an employee should complete the screening prior to the beginning of each shift.
</ul>
<ul>
Screening can be done either by attestation before arrival or on-site at a checkpoint near the entrance
to the facility. 
</ul>

app/views/home/landing.html.erb
<h4>Welcome! <%= @username %></h4>


<div class="card">
  <div class="card-body">
    <h5 class="card-title">Employees:</h5>
    <p class="card-text">Add the people who will be signing in and out, while making attestations to their COVID-19 status</p>
    <%= link_to 'Add/Edit Employees', employees_path, class:"btn btn-primary" %>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Attestations:</h5>
    <p class="card-text">Questions that will be asked to visitors and employees. Use the default attestations or add/edit them according to your local guidlines.</p>
    <%= link_to 'Add/Edit Attestations', questions_path, class:"btn btn-secondary" %>
  </div>
</div>

<br/>
<br/>

<div class="d-grid gap-2 col-6 mx-auto">
  <%= link_to 'Launch Application', home_launch_path, class:"btn btn-primary", notice:"Press F11 to fullscreen, and escape for windowed", data: { confirm: 'To discourage navigation outside of the application: Press F11 to fullscreen the following page, and F11/escape key to return' }%>
</div>

app/views/home/launch.html.erb
<div class="container">

<h4>Who's checking in/out?</h4>

<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= form_tag home_launch_path,class:"d-flex", method: 'get' do %>
  
    <%= text_field_tag :search, params[:search], class:"form-control me-2", placeholder:"First Name" %>
    <%= submit_tag "Search", :name => nil, class:"btn btn-outline-success" %>
  
    <% end %>
  </div>
</nav>
<br/>
<div class="d-grid gap-2 col-6 mx-auto">
  <%= link_to 'Sign in as Guest', new_guest_path, class:"btn btn-primary"%>
</div>
<br/>

<ul class="list-group">
<% if @employees != nil %>
  <% @employees.each do |employee| %>
    <% if employee.user == current_user %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="col-11">
          <span style="font-size: 1.5rem">
            <%=link_to employee.first_name + " " + employee.last_name, home_questionaire_path(:id => employee.id), style:"display:block;text-decoration:none;color:black;" %>
          </span>
          <i><%=link_to employee.title, home_questionaire_path(:id => employee.id), style:"display:block;text-decoration:none;color:grey;" %></i>
        </div>
        <span class="<%= employee.signed_in? ? 'signedIn' : 'signedOut'%>">&#8203;</span>
      </li>      
    <% end %>
  <% end %>
<% end %>
</ul>
<ul class="list-group">
<% if @guests != nil %>
  <% @guests.each do |guest| %>
    <% if guest.user == current_user %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="col-11">
          <span style="font-size: 1.5rem">
            <%=link_to guest.first_name + " " + guest.last_name, home_questionaire_path(:id => guest.id, :guest_name => guest.first_name << guest.last_name), style:"display:block;text-decoration:none;color:black;" %>
          </span>
          <i><%=link_to 'Guest', home_questionaire_path(:id => guest.id, :guest_name => guest.first_name << guest.last_name), style:"display:block;text-decoration:none;color:grey;" %></i>
        </div>
        <span class="<%= guest.signed_in? ? 'signedIn' : 'signedOut'%>">&#8203;</span>
      </li>      
    <% end %>
  <% end %>
<% end %>
</ul>
</div>

app/views/home/questionaire.html.erb
<div style="position: relative;">
    <%= link_to "", home_launch_path, class:"btn-close", style:"position:absolute;top:0;right:0;" %>
    <br/>    
    <%= form_with do |form|%>
        <ul class="container">
            <% @questions.each do |question| %>
                <% if question.user == current_user %>                
                    <li class="row list-group-item-action row-2">
                        <h4 class="col-10"><br/><%= question.attestation %><br/></h4>
                        <div class="col-2"><br/>
                                
                                <%= hidden_field_tag :id, @current_employee.id %>
                                
                                <%= form.radio_button question.id ,question.attestation, :checked => false, class:"btn-check", id:"success-outlined#{question.id}" %>
                                <%= form.label :question, "Yes", class:"btn btn-outline-success", for:"success-outlined#{question.id}" %>
                                
                                <%= form.radio_button question.id , '', :checked => false, class:"btn-check", id:"danger-outlined#{question.id}" %>
                                <%= form.label :question, "No", class:"btn btn-outline-danger", for:"danger-outlined#{question.id}" %>
                            
                            <br/>
                        </div>                    
                    </li>                 
                <% end%>
            <% end %>
        </ul>
        <br/>
        <%= hidden_field_tag :guest_name, @is_guest%>
        <div class="d-grid gap-2 col-6 mx-auto">
        <%= form.submit "Submit", class:"btn btn-primary" %>
        </div>
    <% end %>
    <br/>    
</div>

app/views/home/signoutt.html.erb
<head>
<script type="text/javascript">
function delayedRedirect(){
    window.location = "/home/launch";
}
setTimeout('delayedRedirect()', 2500);
</script>
</head>
<body>
<h1 class="position-absolute top-50 start-50 translate-middle">Signed out Successfully!</h1>
</body>